{
  custom-modules,
  pkgs,
  host,
  lib,
  config,
  merremia,
  inputs,
  ...
}: {
  imports = [
    # Hardware Configuration for this spcific device
    ./hardware-configuration.nix
  ];

  modules = {
    sway.enable = true;
    silent-boot.enable = true;
    gaming.enable = true;
    _1password.enable = true;
    firefox.enable = true;
    quickshell = {
      enable = true;
      developerMode.enable = true;
      monitors = {
        "*" = {};
        "HDMI-A-1" = {
          barWidgets = {
            left = ["workspaces"];
          };
        };
      };
    };
  };

  merremia = let
  in {
    enable = true;
    systemd.enable = true;
    config.colors.colortheme = merremia.lib.readBase16 ./tokyo-city-dark.yaml;
  };

  programs.adb.enable = true;
  users.users.luna.extraGroups = ["adbusers"];

  services.navidrome = {
    enable = true;
    settings = {
      MusicFolder = "/mnt/music";
    };
  };

  systemd.services.navidrome.serviceConfig.BindReadOnlyPaths = ["/mnt/audiobooks"];

  systemd.tmpfiles.settings.navidromeLibs = {
    "/mnt/audiobooks"."d" = {
      mode = ":700";
      user = ":${config.services.navidrome.user}";
      group = ":${config.services.navidrome.group}";
    };
  };

  environment.defaultPackages = with pkgs; [
    usbutils
    wayneko
    krita
  ];

  services.searx = {
    enable = true;
    package = pkgs.searxng;
    environmentFile = "/home/${host.userName}/.searxng.env";
    settings = {
      general = {
        debug = false;
      };
      server = {
        bind_address = "127.0.0.1";
      };
    };
  };

  environment.etc.tabletstuff = {
    target = "udev/rules.d/70-opentabletdriver.rules";
    text = ''

      KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", TAG+="udev-acl"
      KERNEL=="js[0-9]*", SUBSYSTEM=="input", ATTRS{name}=="OpenTabletDriver Virtual Tablet", RUN+="/usr/bin/env rm %E{DEVNAME}"

      # Generated by TabletBot
      KERNEL=="hidraw*", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="091b", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEM=="usb", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="091b", TAG+="uaccess", TAG+="udev-acl"
      SUBSYSTEM=="input", ATTRS{idVendor}=="28bd", ATTRS{idProduct}=="091b", ENV{LIBINPUT_IGNORE_DEVICE}="1"%
    '';
  };

  hardware.opentabletdriver.enable = true;

  programs.wshowkeys.enable = true;

  home-manager.users.${host.userName} = {...}: {
    # Modules
    imports = [
      # Window manager plus all the additional pkgs like waybar
      ../../homemanager-modules/neovim
      ../../homemanager-modules/git
      ../../homemanager-modules/studying
      ../../homemanager-modules/nextcloud-client
      ../../homemanager-modules/man
      ../../homemanager-modules/ncspot
    ];

    home.packages = with pkgs; [
      jq

      sioyek

      rubber
      texliveFull

      discord
      filezilla
      vlc

      heroic
      gamemode
      mangohud
    ];

    wayland.windowManager.sway.config = {
      output = {
        HDMI-A-1 = {
          scale = "1";
          position = "0 0";
          transform = "270";
        };
        DP-2 = {
          scale = "1";
          position = "1080 400";
          mode = "1920x1080@60Hz";
          adaptive_sync = "on";
          modeline = "452.50  1920 2088 2296 2672  1080 1083 1088 1177 -hsync +vsync";
        };
        DP-3 = {
          scale = "1";
          position = "3000 400";
        };
      };

      workspaceOutputAssign = [
        {
          workspace = "10";
          output = "HDMI-A-1";
        }
        {
          workspace = "1";
          output = "DP-2";
        }
        {
          workspace = "2";
          output = "DP-3";
        }
      ];

      startup = [
        # Start 1Password in the background
        {command = "swaymsg exec discord && sleep 3 && swaymsg splitv && swaymsg exec firefox -P messages -no-remote --name Firefox-message && swaymsg splith";}
      ];
    };

    programs.zsh.shellAliases = {
      # Reboot into windows
      reboot-windows = "systemctl reboot --boot-loader-entry=auto-windows";
    };
  };
}
